
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://user:Istakbal@cluster0.du6ovao.mongodb.net/smart-leads?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=yoursupersecretkeyhere123
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

