services:
  - type: web
    name: smart-leads-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: "mongodb+srv://user:Istakbal@cluster0.du6ovao.mongodb.net/smart-leads?retryWrites=true&w=majority&appName=Cluster0"
      - key: JWT_SECRET
        value: "yoursupersecretkeyhere123"

  - type: web
    name: smart-leads-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: smart-leads-backend
          envVarKey: RENDER_EXTERNAL_URL
